# Rest API testing
# Você pode executar este arquivo usando a extensão REST Client no VS Code
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@hostname = http://localhost
@port = 8080
@host = {{hostname}}:{{port}}
@baseUrl = {{host}}/api/v1
@createdAt = {{$datetime iso8601}}

###
POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password123"
}

###
GET {{host}}/users HTTP/1.1
Content-Type: application/json

###
GET {{host}}/users/fad98035-9571-4feb-896b-d8ec53d2851e HTTP/1.1
Content-Type: application/json

###
GET {{host}}/users/email/john.doe.updated@example.com HTTP/1.1
Content-Type: application/json

###
POST {{host}}/users HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "password123",
  "role": "ADMIN"
}

###
POST {{host}}/users HTTP/1.1
Content-Type: application/json

{
  "name": "Maria Silva",
  "email": "maria.silva@example.com",
  "password": "securepassword123"
}

###
POST {{host}}/users HTTP/1.1
Content-Type: application/json

{
  "name": "",
  "email": "",
  "password": ""
}

###
PUT {{host}}/users/c8b56f26-a71f-4e34-b2a8-6dbb21883f52 HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe Updated",
  "email": "john.doe.updated@example.com",
  "password": "newpassword123",
  "role": "USER",
  "active": false
}